{% set name = "seamm-dashboard-client" %}
{% set version = "2023.7.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/seamm_dashboard_client-{{ version }}.tar.gz
  sha256: a908b2b793a9ce96615ce3e919fb53df3760da1e57d1a3d9f03579e27540c9a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6
    - requests
    - requests-toolbelt

test:
  imports:
    - seamm_dashboard_client
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/molssi-seamm/seamm_dashboard_client
  summary: A Python client for the SEAMM Dashboard RESTful API.
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - paulsaxe
